[colors]
primary = { background = "#121212", foreground = "#d4c5b9" }
cursor = { text = "#121212", cursor = "#d8a657" }
selection = { background = "#2d3437", foreground = "#d4c5b9" }

[colors.normal]
black = "#121212"
red = "#c4746e"
green = "#95b572"
yellow = "#c4a657"
blue = "#7c9fa8"
magenta = "#a987a8"
cyan = "#85a585"
white = "#d4c5b9"

[colors.bright]
black = "#665c54"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#8ba4b0"
magenta = "#d3869b"
cyan = "#89b482"
white = "#fbf1c7"
